export const HIPPOMEMO_CSS = [
  '.hippomemo-section[data-plugin="dsh-hippomemo"] { display: flex; flex-direction: column; gap: 16px; padding: 4px 2px 24px; color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-title { margin: 0; color: var(--dsw-alias-label-primary); font-size: 18px; line-height: 26px; font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-intro { margin: 0; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-toolbar { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-toolbar input, [data-plugin="dsh-hippomemo"] .hippomemo-toolbar select { padding: 6px 8px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); font: inherit; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-search { min-width: 240px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-button { border: none; border-radius: 8px; background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); font: inherit; font-size: 13px; line-height: 20px; padding: 6px 10px; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select { display: inline-flex; align-items: center; justify-content: space-between; gap: 8px; min-width: 132px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); font: inherit; font-size: 13px; line-height: 20px; padding: 6px 8px; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select:hover { background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-label { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-chevron { display: inline-flex; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; transition: transform 120ms ease; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-open .hippomemo-select-chevron { transform: rotate(180deg); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-button:hover { background: var(--dsw-alias-interactive-bg-hover-accent, var(--dsw-alias-interactive-bg-hover)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-list { display: flex; flex-direction: column; gap: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card { border: 1px solid var(--dsw-alias-border-l1); border-radius: 14px; background: var(--dsw-alias-bg-layer-2); padding: 12px 14px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-head { display: flex; justify-content: space-between; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-title { color: var(--dsw-alias-label-primary); font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-meta { display: flex; flex-wrap: wrap; gap: 8px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-content { white-space: pre-wrap; margin: 8px 0 0; color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form { display: flex; flex-direction: column; gap: 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form label { display: flex; flex-direction: column; gap: 4px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form input, [data-plugin="dsh-hippomemo"] .hippomemo-form textarea, [data-plugin="dsh-hippomemo"] .hippomemo-form select { border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); padding: 6px 8px; font: inherit; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-error { color: var(--dsw-alias-state-error-primary, var(--dsw-static-red-500)); }',
].join('\n')
